version: '3.8'

services:
  blog-next:
    image: ghcr.io/thomasdsantos/dsantos-blog:latest
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.services.dsantos-blog-next.loadbalancer.server.port=3000
      - traefik.http.routers.dsantos-blog-next.rule=Host(`next.blog.dsantos.fr`)
      - traefik.http.routers.dsantos-blog-next.entrypoints=websecure
      - traefik.http.routers.dsantos-blog-next.tls.certresolver=myresolver
      - traefik.docker.network=traefik-public
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - NODE_ENV=production

networks:
  traefik-public:
    external: true
